// AUTO-GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listAccounts() : Promise<Result<AccountSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAccount(input: NewAccount) : Promise<Result<Account, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_account", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAccount(id: string, patch: AccountPatch) : Promise<Result<Account, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveAccount(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTransactions(filter: TxnFilterInput) : Promise<Result<Transaction[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_transactions", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTransaction(input: NewTransaction) : Promise<Result<Transaction, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_transaction", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransaction(id: string, patch: TxnPatch) : Promise<Result<UpdateTxnResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTransaction(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transaction", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRule(pattern: string, categoryId: string) : Promise<Result<Rule, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule", { pattern, categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategories() : Promise<Result<CategoryDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnboardingState() : Promise<Result<OnboardingState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_onboarding_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedSampleHousehold() : Promise<Result<SeedSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_sample_household") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markOnboardingComplete() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_onboarding_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetOnboardingCompletion() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_onboarding_completion") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearSampleData() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_sample_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitStarterCategories(categories: StarterCategory[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_starter_categories", { categories }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeOllama(baseUrl: string) : Promise<Result<OllamaProbeResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_ollama", { baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLlmProvider(config: LlmProviderConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_llm_provider", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appReady() : Promise<Result<AppReady, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewCsvColumns(path: string, skipHeaderRows: number) : Promise<Result<CsvPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_csv_columns", { path, skipHeaderRows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsv(path: string, accountId: string, mapping: CsvImportMapping) : Promise<Result<ImportSummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv", { path, accountId, mapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listUnfinishedImports() : Promise<Result<Import[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_unfinished_imports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardUnfinishedImport(importId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_unfinished_import", { importId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCompletionProvider(config: CompletionProviderConfig) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_completion_provider", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProviderApiKey(providerId: string, key: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_provider_api_key", { providerId, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderModels(config: CompletionProviderConfig) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_models", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testCompletionProvider(config: CompletionProviderConfig, apiKey: string | null) : Promise<Result<ProviderTestResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_completion_provider", { config, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNeedsReviewCount() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_needs_review_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerCategorize() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_categorize") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategoriesWithSpending() : Promise<Result<CategoryWithSpending[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories_with_spending") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRulesWithCategories() : Promise<Result<RuleWithCategory[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rules_with_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleRule(id: string, enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_rule", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBudgetEnvelopes() : Promise<Result<BudgetEnvelope[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_budget_envelopes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBudget(categoryId: string, amountCents: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_budget", { categoryId, amountCents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGoals() : Promise<Result<GoalDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_goals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createGoal(input: NewGoalInput) : Promise<Result<GoalDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_goal", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGoalBalance(id: string, currentCents: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_goal_balance", { id, currentCents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async archiveGoal(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_goal", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecurring() : Promise<Result<RecurringItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recurring") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReportData() : Promise<Result<ReportData, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_report_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMonthTotals() : Promise<Result<MonthTotals, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_month_totals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runScenario(description: string, months: number, params: ScenarioParamsInput | null) : Promise<Result<ScenarioResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_scenario", { description, months, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScenario(description: string, result: ScenarioResult) : Promise<Result<SavedScenario, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_scenario", { description, result }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listScenarioHistory() : Promise<Result<SavedScenario[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_scenario_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteScenario(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_scenario", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTransactionCount() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transaction_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Account = { id: string; owner: string; bank: string; type: AccountType; name: string; last4: string | null; currency: string; color: string; archived_at: string | null; created_at: string }
export type AccountPatch = { name: string | null; bank: string | null; account_type: AccountType | null; color: string | null; last4: string | null; currency: string | null }
export type AccountSummary = { id: string; owner: string; bank: string; type: AccountType; name: string; balance_cents: number; currency: string; color: string; source: string }
export type AccountType = "Checking" | "Savings" | "Credit" | "Investment" | "Cash" | "Other"
export type AmountConvention = "negative_is_outflow" | "positive_is_outflow" | "split_debit_credit"
/**
 * Frontend-facing error. `code` is machine-readable (e.g. `core.db.locked`);
 * `message` is human-readable; `details` is structured context for logging
 * and possible inline rendering.
 */
export type AppError = { code: string; message: string; details?: JsonValue | null }
export type AppReady = { version: string }
/**
 * One category's budget + actual for a month.
 */
export type BudgetEnvelope = { categoryId: string; categoryLabel: string; categoryColor: string; groupLabel: string; 
/**
 * Budget set by user (0 = not budgeted)
 */
budgetCents: number; 
/**
 * Actual outflow this month (positive = spent)
 */
spentCents: number; txnCount: number }
export type CategoryDto = { id: string; label: string; color: string; group_id: string; group_label: string }
/**
 * One category's 12-month total.
 */
export type CategoryTotal = { categoryId: string; label: string; color: string; totalCents: number; txnCount: number }
/**
 * Category with real spending aggregated from transactions.
 */
export type CategoryWithSpending = { id: string; label: string; color: string; groupId: string; groupLabel: string; 
/**
 * Total outflow this calendar month (positive = money spent)
 */
thisMonthCents: number; 
/**
 * Total outflow last calendar month
 */
lastMonthCents: number; 
/**
 * Number of transactions categorised here this month
 */
txnCount: number; yearTotalCents: number; budgetCents: number }
export type ColumnRole = "Date" | "Amount" | "Merchant" | "Notes" | "Category" | "Skip" | "Debit" | "Credit"
export type CompletionProviderConfig = { kind: "unconfigured" } | { kind: "ollama"; base_url: string; model: string } | { kind: "openai_compat"; preset: string; base_url: string; model: string } | { kind: "anthropic"; model: string }
export type CsvImportMapping = { skip_header_rows: number; columns: ColumnRole[]; date_format: string; amount_convention: AmountConvention; decimal_separator?: string; delimiter?: string | null }
export type CsvPreview = { headers: string[] | null; rows: string[][]; detected_delimiter: string; total_rows: number; encoding_note: string | null }
export type GoalDto = { id: string; name: string; goalType: string; targetCents: number; currentCents: number; monthlyCents: number; targetDate: string | null; color: string; notes: string | null; sortOrder: number; createdAt: string }
export type Import = { id: string; source: ImportSource; filename: string | null; account_id: string | null; started_at: string; finished_at: string | null; rows_imported: number; rows_skipped_duplicates: number; error: string | null }
export type ImportSource = "csv" | "manual" | "sample"
export type ImportSummary = { import_id: string; rows_imported: number; rows_skipped_duplicates: number; errors: RowError[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LlmProviderConfig = { kind: "ollama"; base_url: string; completion_model: string; embedding_model: string } | { kind: "unconfigured" }
/**
 * One merchant's 12-month total.
 */
export type MerchantTotal = { merchantRaw: string; categoryLabel: string; categoryColor: string; totalCents: number; txnCount: number }
/**
 * One month's summary for the bar chart.
 */
export type MonthSummary = { 
/**
 * "YYYY-MM"
 */
month: string; 
/**
 * Human label e.g. "Jan"
 */
label: string; 
/**
 * Total inflows (positive transactions), as positive cents
 */
incomeCents: number; 
/**
 * Total outflows (negative transactions), as positive cents
 */
expenseCents: number; 
/**
 * Net = income - expense
 */
netCents: number }
/**
 * Lightweight summary for the Today screen.
 */
export type MonthTotals = { incomeCents: number; expenseCents: number; netCents: number; savingsRatePct: number; 
/**
 * Number of transactions this month
 */
txnCount: number }
export type NewAccount = { owner: string; bank: string; type: AccountType; name: string; last4: string | null; currency: string; color: string; opening_balance_cents: number; source?: string }
export type NewGoalInput = { name: string; goalType: string; targetCents: number; monthlyCents: number; targetDate: string | null; color: string; notes: string | null }
export type NewTransaction = { account_id: string; posted_at: string; amount_cents: number; merchant_raw: string; category_id: string | null; notes: string | null; status: TransactionStatus }
export type OllamaProbeResult = { reachable: boolean; models: string[]; has_nomic_embed: boolean }
export type OnboardingState = { account_count: number; category_count: number; completion_marked: boolean }
export type ProposedRuleDto = { pattern: string; category_id: string; category_label: string }
export type ProviderTestResult = { ok: boolean; error: string | null; latency_ms: number }
/**
 * A recurring transaction detected from transaction history.
 */
export type RecurringItem = { merchantRaw: string; categoryLabel: string; categoryColor: string; 
/**
 * Most recent amount (negative = expense, positive = income)
 */
lastAmountCents: number; 
/**
 * Average gap between occurrences in days
 */
avgGapDays: number; 
/**
 * How many times this has appeared
 */
occurrences: number; 
/**
 * Most recent posted_at date (ISO)
 */
lastSeen: string; 
/**
 * Estimated next date (ISO), based on last_seen + avg_gap
 */
nextExpected: string; 
/**
 * "monthly" | "weekly" | "biweekly" | "annual" | "irregular"
 */
cadence: string; 
/**
 * Whether this looks like a subscription (small, regular negative charge)
 */
isSubscription: boolean }
export type ReportData = { 
/**
 * Last 12 months, oldest first
 */
monthly: MonthSummary[]; 
/**
 * Top 10 categories by 12-month spend
 */
topCategories: CategoryTotal[]; 
/**
 * Top 10 merchants by 12-month spend
 */
topMerchants: MerchantTotal[] }
export type RowError = { row_number: number; reason: string }
export type Rule = { id: string; pattern: string; category_id: string; enabled: boolean; source: string; created_at: string }
/**
 * Rule with resolved category label and color.
 */
export type RuleWithCategory = { id: string; pattern: string; categoryId: string; categoryLabel: string; categoryColor: string; enabled: boolean; source: string; createdAt: string }
export type SavedScenario = { id: string; description: string; result: ScenarioResult; createdAt: string }
export type ScenarioParamsInput = { incomeDeltaPct: number; monthlyExpenseDeltaCents: number; oneTimeCents: number; startMonthOffset: number; label: string }
export type ScenarioResult = { verdict: boolean; runwayChangeDays: number; monthlyImpactCents: number; considerations: string[]; baselineMonthly: number[]; scenarioMonthly: number[]; goalsAffected: string[] }
export type SeedSummary = { accounts_created: number; transactions_created: number; import_id: string }
export type StarterCategory = { id: string; label: string; group_id: string }
export type Transaction = { id: string; account_id: string; posted_at: string; amount_cents: number; merchant_raw: string; merchant_id: string | null; merchant_label: string | null; merchant_color: string | null; merchant_initials: string | null; category_id: string | null; category_label: string | null; category_color: string | null; status: TransactionStatus; notes: string | null; ai_confidence: number | null; ai_explanation: string | null; is_anomaly: boolean; created_at: string }
export type TransactionStatus = "cleared" | "pending" | "manual"
export type TxnFilterInput = { accountId: string | null; limit: number | null; offset: number | null; search: string | null; filterPreset: string | null }
export type TxnPatch = { notes: string | null; category_id: string | null; amount_cents: number | null; merchant_raw: string | null }
export type UpdateTxnResult = { transaction: Transaction; proposed_rule: ProposedRuleDto | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
