// AUTO-GENERATED by export_bindings. Do not edit.
// Source of truth: crates/finsight-api/src/sink.rs (event_names).

export const COPILOT_STREAM_FRAME = "copilot-stream-frame";
export const COPILOT_ASYNC_ANSWER = "copilot-async-answer";
export const IMPORT_PROGRESS = "import-progress";
export const IMPORT_COMPLETE = "import-complete";
export const CATEGORIZATION_PROGRESS = "categorization.progress";
export const CATEGORIZATION_COMPLETE = "categorization.complete";
export const AGENT_ERROR = "agent.error";
export const FINSIGHT_KEEPALIVE = "finsight:keepalive";
export const FINSIGHT_AUTH_REQUIRED = "finsight:auth-required";

/** Every wire event name shared between backend and frontend. */
export const EVENT_NAMES = [COPILOT_STREAM_FRAME, COPILOT_ASYNC_ANSWER, IMPORT_PROGRESS, IMPORT_COMPLETE, CATEGORIZATION_PROGRESS, CATEGORIZATION_COMPLETE, AGENT_ERROR, FINSIGHT_KEEPALIVE, FINSIGHT_AUTH_REQUIRED] as const;
export type EventName = (typeof EVENT_NAMES)[number];
