use std::collections::{BTreeMap, BTreeSet};

/// Parse `bindings.ts` into cmd → set(camelCase arg keys). Matches the two shapes
/// tauri-specta emits: `TAURI_INVOKE("cmd")` and `TAURI_INVOKE("cmd", { a, b })`.
fn parse_bindings() -> BTreeMap<String, BTreeSet<String>> {
    let src = include_str!("../../../ui/src/api/bindings.ts");
    let mut out = BTreeMap::new();
    for chunk in src.split("TAURI_INVOKE(\"").skip(1) {
        let cmd = chunk.split('"').next().unwrap().to_string();
        // Args object (if any) is the `{ ... }` before the first `)` after the name.
        let head = &chunk[..chunk.find(')').unwrap_or(chunk.len())];
        let mut keys = BTreeSet::new();
        if let (Some(o), Some(c)) = (head.find('{'), head.rfind('}')) {
            for raw in head[o + 1..c].split(',') {
                // shorthand `{ id, balanceCents }` OR `{ id: id }` — take the key.
                let k = raw.split(':').next().unwrap().trim();
                if !k.is_empty() {
                    keys.insert(k.to_string());
                }
            }
        }
        out.insert(cmd, keys);
    }
    out
}

#[test]
fn every_binding_command_is_routed_or_explicitly_unsupported() {
    let wanted: BTreeSet<String> = parse_bindings().keys().cloned().collect();
    assert!(
        wanted.len() > 100,
        "bindings parse looks broken: {}",
        wanted.len()
    );
    let routed: BTreeSet<String> = finsight_server::dispatch::SUPPORTED
        .iter()
        .chain(finsight_server::dispatch::UNSUPPORTED)
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = wanted.difference(&routed).collect();
    let stale: Vec<_> = routed.difference(&wanted).collect();
    assert!(
        missing.is_empty(),
        "bindings.ts commands with no server route: {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "server routes for commands not in bindings.ts: {stale:?}"
    );
}

/// Task 4 guard: SUPPORTED is generated by `rpc_routes!` from the same table as
/// the match arms, so it must equal the bindings `collect_commands!` set exactly.
/// No regex parsing of dispatch.rs — count + membership is the whole contract.
#[test]
fn supported_matches_collect_commands() {
    assert_eq!(
        finsight_server::dispatch::SUPPORTED.len(),
        finsight_bindings::COMMAND_COUNT,
        "SUPPORTED.len() {} != COMMAND_COUNT {} — rpc_routes! table drifted from collect_commands!",
        finsight_server::dispatch::SUPPORTED.len(),
        finsight_bindings::COMMAND_COUNT
    );
    let supported: BTreeSet<String> = finsight_server::dispatch::SUPPORTED
        .iter()
        .copied()
        .map(|s: &str| s.to_string())
        .collect();
    let expected: BTreeSet<String> = finsight_bindings::COMMANDS
        .iter()
        .copied()
        .map(|s: &str| s.to_string())
        .collect();
    let missing: Vec<_> = expected.difference(&supported).cloned().collect();
    let stale: Vec<_> = supported.difference(&expected).cloned().collect();
    assert!(
        missing.is_empty(),
        "commands in bindings but not in SUPPORTED (add rpc_routes! arm): {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "commands in SUPPORTED but not in bindings (stale rpc_routes! arm): {stale:?}"
    );
}

#[test]
fn openapi_commands_match_dispatch_supported() {
    let openapi: BTreeSet<String> = finsight_openapi::COMMANDS.iter().map(|s| s.to_string()).collect();
    let routed: BTreeSet<String> = finsight_server::dispatch::SUPPORTED.iter().map(|s| s.to_string()).collect();
    let missing: Vec<_> = openapi.difference(&routed).collect();
    let stale: Vec<_> = routed.difference(&openapi).collect();
    assert!(
        missing.is_empty(),
        "finsight_openapi::COMMANDS has entries not in dispatch SUPPORTED: {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "dispatch SUPPORTED has entries not in finsight_openapi::COMMANDS: {stale:?}"
    );
}

#[test]
fn openapi_json_paths_match_commands() {
    let spec = finsight_openapi::build_openapi();
    let paths = spec["paths"].as_object().expect("paths must be object");
    let openapi_cmds: BTreeSet<String> = finsight_openapi::COMMANDS.iter().map(|s| s.to_string()).collect();
    for cmd in &openapi_cmds {
        let key = format!("/api/rpc/{cmd}");
        assert!(paths.contains_key(&key), "openapi.json missing {key}");
    }
    let rpc_paths = paths.keys().filter(|k| k.starts_with("/api/rpc/")).count();
    assert_eq!(
        rpc_paths,
        openapi_cmds.len(),
        "openapi rpc path count must equal COMMANDS.len()"
    );
}

/// Event-name contract guard: the generated `ui/src/api/eventNames.ts` must
/// contain exactly the names in `finsight_api::sink::event_names::ALL`. Catches
/// a stale generation step after adding/renaming a backend event (the class of
/// drift that used to break streaming/import UX silently at runtime).
#[test]
fn generated_event_names_match_the_rust_contract() {
    let src = include_str!("../../../ui/src/api/eventNames.ts");
    let ts_names: BTreeSet<String> = src
        .lines()
        .filter(|l| l.contains('"'))
        .map(|l| l.split('"').nth(1).unwrap().to_string())
        .collect();
    assert!(
        ts_names.len() > 5,
        "eventNames.ts parse looks broken: {ts_names:?}"
    );
    let rust: BTreeSet<String> = finsight_api::sink::event_names::ALL
        .iter()
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = rust.difference(&ts_names).collect();
    let stale: Vec<_> = ts_names.difference(&rust).collect();
    assert!(
        missing.is_empty() && stale.is_empty(),
        "eventNames.ts drifted from finsight_api::sink::event_names — \
         rerun `cargo run -p finsight-bindings --bin export_bindings`: \
         missing={missing:?} stale={stale:?}"
    );
}
