use std::collections::BTreeSet;

#[test]
fn every_openapi_command_is_routed_or_explicitly_unsupported() {
    let wanted: BTreeSet<String> = finsight_openapi::COMMANDS
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert!(
        wanted.len() > 100,
        "openapi COMMANDS looks broken: {}",
        wanted.len()
    );
    let routed: BTreeSet<String> = finsight_server::dispatch::SUPPORTED
        .iter()
        .chain(finsight_server::dispatch::UNSUPPORTED)
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = wanted.difference(&routed).collect();
    let stale: Vec<_> = routed.difference(&wanted).collect();
    assert!(
        missing.is_empty(),
        "openapi COMMANDS with no server route: {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "server routes for commands not in openapi: {stale:?}"
    );
}

/// SUPPORTED is generated by `rpc_routes!` from the same table as the match arms,
/// so it must equal the openapi `COMMANDS` set exactly.
#[test]
fn supported_matches_openapi() {
    assert_eq!(
        finsight_server::dispatch::SUPPORTED.len(),
        finsight_openapi::COMMANDS.len(),
        "SUPPORTED.len() {} != COMMANDS.len() {} — rpc_routes! table drifted from openapi!",
        finsight_server::dispatch::SUPPORTED.len(),
        finsight_openapi::COMMANDS.len()
    );
    let supported: BTreeSet<String> = finsight_server::dispatch::SUPPORTED
        .iter()
        .copied()
        .map(|s: &str| s.to_string())
        .collect();
    let expected: BTreeSet<String> = finsight_openapi::COMMANDS
        .iter()
        .copied()
        .map(|s: &str| s.to_string())
        .collect();
    let missing: Vec<_> = expected.difference(&supported).cloned().collect();
    let stale: Vec<_> = supported.difference(&expected).cloned().collect();
    assert!(
        missing.is_empty(),
        "commands in openapi but not in SUPPORTED (add rpc_routes! arm): {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "commands in SUPPORTED but not in openapi (stale rpc_routes! arm): {stale:?}"
    );
}

#[test]
fn openapi_commands_match_dispatch_supported() {
    let openapi: BTreeSet<String> = finsight_openapi::COMMANDS
        .iter()
        .map(|s| s.to_string())
        .collect();
    let routed: BTreeSet<String> = finsight_server::dispatch::SUPPORTED
        .iter()
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = openapi.difference(&routed).collect();
    let stale: Vec<_> = routed.difference(&openapi).collect();
    assert!(
        missing.is_empty(),
        "finsight_openapi::COMMANDS has entries not in dispatch SUPPORTED: {missing:?}"
    );
    assert!(
        stale.is_empty(),
        "dispatch SUPPORTED has entries not in finsight_openapi::COMMANDS: {stale:?}"
    );
}

#[test]
fn openapi_json_paths_match_commands() {
    let spec = finsight_openapi::build_openapi_value();
    let paths = spec["paths"].as_object().expect("paths must be object");
    let openapi_cmds: BTreeSet<String> = finsight_openapi::COMMANDS
        .iter()
        .map(|s| s.to_string())
        .collect();
    for cmd in &openapi_cmds {
        let key = format!("/api/rpc/{cmd}");
        assert!(paths.contains_key(&key), "openapi.json missing {key}");
    }
    let rpc_paths = paths.keys().filter(|k| k.starts_with("/api/rpc/")).count();
    assert_eq!(
        rpc_paths,
        openapi_cmds.len(),
        "openapi rpc path count must equal COMMANDS.len()"
    );
}

#[test]
fn openapi_json_files_are_identical() {
    let root = include_str!("../../../openapi.json");
    let ui = include_str!("../../../ui/src/api/openapi.json");
    assert_eq!(
        root, ui,
        "openapi.json and ui/src/api/openapi.json must be identical — run `cargo run -p finsight-openapi --bin export_openapi`"
    );
}

#[test]
fn transfer_envelope_is_unknown_command() {
    assert!(
        !finsight_openapi::COMMANDS.contains(&"transfer_envelope"),
        "transfer_envelope must be absent from openapi COMMANDS (I4) — use transfer_budget"
    );
    assert!(
        !finsight_server::dispatch::SUPPORTED.contains(&"transfer_envelope"),
        "transfer_envelope must not be in SUPPORTED"
    );
    assert!(
        !finsight_server::dispatch::UNSUPPORTED.contains(&"transfer_envelope"),
        "transfer_envelope must not be in UNSUPPORTED either — it is deleted"
    );
}

/// Event-name contract guard: the generated `ui/src/api/eventNames.ts` must
/// contain exactly the names in `finsight_api::sink::event_names::ALL`. Catches
/// a stale generation step after adding/renaming a backend event (the class of
/// drift that used to break streaming/import UX silently at runtime).
#[test]
fn generated_event_names_match_the_rust_contract() {
    let src = include_str!("../../../ui/src/api/eventNames.ts");
    let ts_names: BTreeSet<String> = src
        .lines()
        .filter(|l| l.contains('"'))
        .map(|l| l.split('"').nth(1).unwrap().to_string())
        .collect();
    assert!(
        ts_names.len() > 5,
        "eventNames.ts parse looks broken: {ts_names:?}"
    );
    let rust: BTreeSet<String> = finsight_api::sink::event_names::ALL
        .iter()
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = rust.difference(&ts_names).collect();
    let stale: Vec<_> = ts_names.difference(&rust).collect();
    assert!(
        missing.is_empty() && stale.is_empty(),
        "eventNames.ts drifted from finsight_api::sink::event_names — \
         rerun `cargo run -p finsight-openapi --bin export_openapi` (and rebuild eventNames): \
         missing={missing:?} stale={stale:?}"
    );
}

/// Tool-name contract guard: the `ui/src/api/toolNames.ts` mirror must contain
/// exactly the names in `finsight_agent::reasoning::tools::names::ALL_TOOL_NAMES`.
/// Same drift class as the event-names guard above: a backend rename that
/// compiles everywhere but silently breaks the Copilot toolkit registration.
#[test]
fn generated_tool_names_match_the_rust_contract() {
    let src = include_str!("../../../ui/src/api/toolNames.ts");
    let ts_names: BTreeSet<String> = src
        .lines()
        .filter(|l| l.contains('"'))
        .map(|l| l.split('"').nth(1).unwrap().to_string())
        .collect();
    assert!(
        ts_names.len() > 40,
        "toolNames.ts parse looks broken: {ts_names:?}"
    );
    let rust: BTreeSet<String> = finsight_agent::reasoning::tools::names::ALL_TOOL_NAMES
        .iter()
        .map(|s| s.to_string())
        .collect();
    let missing: Vec<_> = rust.difference(&ts_names).collect();
    let stale: Vec<_> = ts_names.difference(&rust).collect();
    assert!(
        missing.is_empty() && stale.is_empty(),
        "toolNames.ts drifted from reasoning::tools::names::ALL_TOOL_NAMES — \
         update ui/src/api/toolNames.ts to match: \
         missing={missing:?} stale={stale:?}"
    );
}
